services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "5173:5000"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
        - path: ./eslint.config.js
          action: rebuild
        - path: .
          target: /app/client
          action: sync
  
  server:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
    ports:
      - "8080:80"



