spring:
    application:
        name: catalog
    datasource:
        generate-unique-name: false
        name: moviedb
    main:
        allow-bean-definition-overriding: true
    session:
        jdbc:
            initialize-schema: always

server:
    servlet:
        session:
            cookie:
                same-site: lax

rsa:
    private-key: classpath:certs/private.pem
    public-key: classpath:certs/public.pem
